#!/usr/bin/env bash
set -euo pipefail

ROOT="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")/.." && pwd)"
LOCAL="${ROOT}/.local/toolchain"
BIN="${LOCAL}/bin"
DL="${LOCAL}/downloads"
APPS="${LOCAL}/apps"

CTRTOOL_URL='https://github.com/3DSGuy/Project_CTR/releases/download/ctrtool-v1.3.0/ctrtool-v1.3.0-ubuntu_x86_64.zip'
CTRTOOL_SHA='f553194b0ab2b539457160231cf5651c554e148f17ec960fae63424e82582aa8'
MAKEROM_URL='https://github.com/3DSGuy/Project_CTR/releases/download/makerom-v0.19.0/makerom-v0.19.0-ubuntu_x86_64.zip'
MAKEROM_SHA='287b809dec064e0ad597e3d272c49ecb7eed41693d5ee6fef9d8a8aa24c2497e'
AZAHAR_URL='https://github.com/azahar-emu/azahar/releases/download/2126.1.1/azahar.AppImage'
AZAHAR_SHA='e445dabc18fe7665867e24a18a78e24e133261a9cc320fae6a4a45bd2e7c4783'
GHIDRA_URL='https://github.com/NationalSecurityAgency/ghidra/releases/download/Ghidra_12.1.3_build/ghidra_12.1.3_PUBLIC_20260817.zip'
GHIDRA_SHA='93a5d11a9ad510622acaaf908c556a7b9b764d338e78a7567f3689bf5081fd54'

have() { command -v "$1" >/dev/null 2>&1; }
check() {
    echo "repo: $ROOT"
    for x in git python3 cmake ninja gcc g++ clang llvm-objdump java unzip tar sha256sum; do
        if have "$x"; then printf '[ok]      %-14s %s\n' "$x" "$(command -v "$x")"; else printf '[missing] %-14s\n' "$x"; fi
    done
    if have curl || have wget; then echo '[ok]      downloader'; else echo '[missing] downloader (curl/wget)'; fi
    for x in ctrtool makerom azahar ghidra; do
        [[ -x "$BIN/$x" ]] && printf '[local]   %-14s %s\n' "$x" "$BIN/$x" || printf '[missing] %-14s\n' "$x"
    done
}

if [[ "${1:-}" == '--check' ]]; then check; exit 0; fi
[[ -z "${1:-}" ]] || { echo 'usage: bash tools/setup_environment.sh [--check]' >&2; exit 2; }
[[ "$(uname -s)" == Linux && "$(uname -m)" == x86_64 ]] || { echo 'error: installer currently targets Linux x86_64' >&2; exit 1; }
for x in python3 unzip tar sha256sum java; do have "$x" || { echo "error: bootstrap tool missing: $x" >&2; exit 1; }; done
have curl || have wget || { echo 'error: curl or wget is required' >&2; exit 1; }
JAVA_MAJOR="$(java -version 2>&1 | sed -n '1s/.*version "\([0-9][0-9]*\).*/\1/p')"
[[ "$JAVA_MAJOR" =~ ^[0-9]+$ ]] && (( JAVA_MAJOR >= 21 )) || { echo 'error: Ghidra 12.1.3 requires a 64-bit JDK 21+' >&2; exit 1; }
mkdir -p "$BIN" "$DL" "$APPS"

download() {
    if have curl; then curl -fL --retry 3 -o "$2" "$1"; else wget --tries=3 -O "$2" "$1"; fi
}
verified() {
    local url="$1" sha="$2" out="$3"
    [[ -f "$out" ]] || download "$url" "$out"
    printf '%s  %s\n' "$sha" "$out" | sha256sum -c --status || { rm -f "$out"; echo "error: SHA-256 mismatch: $out" >&2; exit 1; }
}

CTR_ZIP="$DL/ctrtool-1.3.0.zip"
MAKE_ZIP="$DL/makerom-0.19.0.zip"
verified "$CTRTOOL_URL" "$CTRTOOL_SHA" "$CTR_ZIP"
verified "$MAKEROM_URL" "$MAKEROM_SHA" "$MAKE_ZIP"
TMP="$LOCAL/.tmp-project-ctr"; rm -rf "$TMP"; mkdir -p "$TMP/ctr" "$TMP/make"
unzip -q -o "$CTR_ZIP" -d "$TMP/ctr"; unzip -q -o "$MAKE_ZIP" -d "$TMP/make"
CTR_BIN="$(find "$TMP/ctr" -type f -name ctrtool -print -quit)"; MAKE_BIN="$(find "$TMP/make" -type f -name makerom -print -quit)"
[[ -n "$CTR_BIN" && -n "$MAKE_BIN" ]] || { echo 'error: Project_CTR archive layout unexpected' >&2; exit 1; }
install -m 0755 "$CTR_BIN" "$BIN/ctrtool"; install -m 0755 "$MAKE_BIN" "$BIN/makerom"; rm -rf "$TMP"

AZ="$APPS/azahar-2126.1.1.AppImage"
verified "$AZAHAR_URL" "$AZAHAR_SHA" "$AZ"; chmod 0755 "$AZ"
cat > "$BIN/azahar" <<EOF_AZ
#!/usr/bin/env bash
exec "$AZ" --appimage-extract-and-run "\$@"
EOF_AZ
chmod 0755 "$BIN/azahar"

GH_ZIP="$DL/ghidra-12.1.3.zip"; GH="$APPS/ghidra-12.1.3"
verified "$GHIDRA_URL" "$GHIDRA_SHA" "$GH_ZIP"
TMP="$LOCAL/.tmp-ghidra"; rm -rf "$TMP" "$GH"; mkdir -p "$TMP"; unzip -q "$GH_ZIP" -d "$TMP"
GH_SRC="$(find "$TMP" -mindepth 1 -maxdepth 1 -type d -print -quit)"; [[ -n "$GH_SRC" ]] || { echo 'error: Ghidra archive layout unexpected' >&2; exit 1; }
mv "$GH_SRC" "$GH"; rm -rf "$TMP"
cat > "$BIN/ghidra" <<EOF_GH
#!/usr/bin/env bash
exec "$GH/ghidraRun" "\$@"
EOF_GH
chmod 0755 "$BIN/ghidra"

cat > "$LOCAL/env.sh" <<EOF_ENV
# Generated by tools/setup_environment.sh
export GEN6_TOOLCHAIN_ROOT="$LOCAL"
export PATH="$BIN:\${PATH}"
EOF_ENV

echo "installed: $LOCAL"
echo 'activate: source .local/toolchain/env.sh'
echo 'tools: ctrtool, makerom, Azahar, Ghidra; system LLVM/Clang/Python/CMake/Ninja are reused.'
echo 'ROM images, decrypted retail binaries, and console/title keys are never downloaded by this installer.'
